# Generated by Django 3.2.9 on 2021-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211204_1444'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
