# Generated by Django 3.2.9 on 2022-01-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211223_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='link_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
