# Generated by Django 3.2.9 on 2022-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_patient_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
            preserve_default=False,
        ),
    ]
