# Generated by Django 3.2.9 on 2022-04-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220223_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
