# Generated by Django 3.2.9 on 2022-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220223_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cpfc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
