# Generated by Django 3.2.9 on 2022-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_patient_cpfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cpfc',
        ),
        migrations.AddField(
            model_name='patient',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='carbohydrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
