# Generated by Django 3.2.9 on 2022-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_historicalpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
