# Generated by Django 3.2.9 on 2022-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_doctor_contact_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpatient',
            old_name='link_token',
            new_name='user_activate_token',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='link_token',
            new_name='user_activate_token',
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
