image: python:3.9

stages:
  - lint
  - tests
  - build
  - deploy

lint:
  stage: lint
  script:
    - pip install click==8.0.1
    - pip install black==21.7b0
    - black . --check --diff

run_tests:
  stage: tests
  image: atnartur/docker:latest
  script:
    - docker-compose -f docker-compose.test.yml -p backend_testing_${CI_COMMIT_SHA} build
    - >
      docker-compose -f docker-compose.test.yml -p backend_testing_${CI_COMMIT_SHA}
      run app /bin/bash -c "python manage.py migrate && pytest --cov=."
  after_script:
      - docker-compose -f docker-compose.test.yml -p backend_testing_${CI_COMMIT_SHA} down -v
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'


build:
  stage: build
  script:
    - docker-compose -f docker-compose.prod.yml build
  tags:
    - med_platform
  only:
    - feature/docker

deploy_linux:
  stage: deploy
  script:
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml rm -f
    - docker-compose -f docker-compose.prod.yml up -d
  tags:
    - med_platform
  only:
    - feature/docker

# deploy:
#   stage: deploy
#   script:
#     # Скрипт сборки указан внутри системы и
#     # никаких дополнительных настроек не требуется
#     - echo
#   tags:
#     - a.uenv.ru
#     - unienv_deploy
#   environment:
#     name: UniEnv
#     url: http://a.uenv.ru
#   only:
#     variables:
#       - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
