image: python:3.8.12

stages:
  - lint
  - tests
  - build
  - deploy

lint:
  stage: lint
  script:
    - pip install click==8.0.1
    - pip install black==21.7b0
    - black . --check --diff

run_tests:
  stage: tests
  image: docker/compose:latest
  script:
    - docker-compose -f docker-compose.test.yml up -d
    - docker-compose exec coverage run -m pytest
    - docker-compose exec coverage report
    - docker-compose exec coverage xml
  after_script:
      - docker-compose -f docker-compose.test.yml down
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: build
  script:
    - docker-compose -f docker-compose.prod.yml build
  tags:
    - med_platform
  only:
    - feature/docker

deploy_linux:
  stage: deploy
  script:
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml rm -f
    - docker-compose -f docker-compose.prod.yml up -d
  tags:
    - med_platform
  only:
    - feature/docker

deploy:
  stage: deploy_old
  script:
    # Скрипт сборки указан внутри системы и
    # никаких дополнительных настроек не требуется
    - echo
  tags:
    - a.uenv.ru
    - unienv_deploy
  environment:
    name: UniEnv
    url: http://a.uenv.ru
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
