image: atnartur/docker:latest

services:
- docker:dind

stages:
  - lint
  - deploy_unienv
  - build
  - deploy_yandex

lint:
  stage: lint
  script:
    - pip install click==8.0.1
    - pip install black==21.7b0
    - black . --check --diff


deploy:
   image: python:3.8.12
   stage: deploy_unienv
   script:
     # Скрипт сборки указан внутри системы и
     # никаких дополнительных настроек не требуется
     - echo
   tags:
     - a.uenv.ru
     - unienv_deploy
   environment:
     name: UniEnv
     url: http://a.uenv.ru
   only:
     variables:
       - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME


build:
  stage: build
  script:
    - echo $ENV_FILE_FOR_PROD
    - docker-compose -f docker-compose.prod.yml build
  tags:
    - med_platform
  only:
    - develop

deploy_linux:
  stage: deploy_yandex
  script:
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml rm -f
    - docker-compose -f docker-compose.prod.yml up -d
  tags:
    - med_platform
  only:
    - develop
