image: atnartur/docker:latest

services:
- docker:dind

stages:
  - lint
  # - deploy_unienv
  - build
  - deploy_yandex

lint:
  image: python:3.8.12
  stage: lint
  script:
    - pip install click==8.0.1
    - pip install black==21.7b0
    - black . --check --diff

build:
  stage: build
  script:
    - echo $ENV_FILE_FOR_PROD
    - docker-compose -f docker-compose.prod.yml build
  tags:
    - med_platform
  only:
    - develop

deploy_linux:
  stage: deploy_yandex
  script:
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml rm -f
    - docker-compose -f docker-compose.prod.yml up -d
  tags:
    - med_platform
  only:
    - develop
