image: python:3.8.12

stages:
  - lint
  - deploy
  - test

lint:
  stage: lint
  script:
    - pip install click==8.0.1
    - pip install black==21.7b0
    - pip install pytest==7.1.2
    - black . --check --diff

pytest:
  stage: test
  script:
  - pytest -v

deploy:
  stage: deploy
  script:
    # Скрипт сборки указан внутри системы и
    # никаких дополнительных настроек не требуется
    - echo
  tags:
    - a.uenv.ru
    - unienv_deploy
  environment:
    name: UniEnv
    url: http://a.uenv.ru
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
