image: atnartur/docker:latest

services:
- docker:dind

stages:
  - lint
  - tests
  # - deploy_unienv
  - build
  - deploy_yandex

lint:
  image: python:3.8.12
  stage: lint
  script:
    - pip install click==8.0.1
    - pip install black==21.7b0
    - black . --check --diff

run_tests:
  stage: tests
  image: atnartur/docker:latest
  script:
    - docker-compose -f docker-compose.test.yml -p backend_testing_${CI_COMMIT_SHA} build
    - >
      docker-compose -f docker-compose.test.yml -p backend_testing_${CI_COMMIT_SHA}
      run app /bin/bash -c "python manage.py migrate && pytest --cov=."
  after_script:
      - docker-compose -f docker-compose.test.yml -p backend_testing_${CI_COMMIT_SHA} down -v
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'


build:
  stage: build
  script:
    - echo $ENV_FILE_FOR_PROD
    - docker-compose -f docker-compose.prod.yml build
  tags:
    - med_platform
  only:
    - develop

deploy_linux:
  stage: deploy_yandex
  script:
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml rm -f
    - docker-compose -f docker-compose.prod.yml up -d
  tags:
    - med_platform
  only:
    - develop
