version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      DB_NAME: med
      DB_USER: med
      DB_PASSWORD: med
      DB_HOST: db
      EMAIL_HOST: ${EMAIL_HOST}

      REDIS_URL: redis://172.17.0.2:6379/0

    networks:
      - backend
    restart: always

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_NAME: med
      POSTGRES_PASSWORD: med
      POSTGRES_USER: med
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data3b
    restart: always

  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data
    restart: always
    networks:
      - backend
    environment:
      REDIS_URL: redis://172.17.0.2:6379/0
    expose:
      - 6379

  celery:
    build:
      context: .
    environment:
      REDIS_URL: redis://172.17.0.2:6379/0
    networks:
      - backend
    depends_on:
      - redis
      - app
    command: celery -A med_communication_platform worker -l INFO

volumes:
  db:
  redis:

networks:
  backend:
    driver: bridge