version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always

  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data3b
    restart: always

  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data
    restart: always
    env_file:
      - .env
    expose:
      - 6379

  celery:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - redis
      - app
    command: celery -A med_communication_platform worker -l INFO

volumes:
  db:
  redis:
