# Generated by Django 3.2.9 on 2022-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydish',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
