# Generated by Django 3.2.9 on 2022-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_additionaldaydish'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydish',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AdditionalDayDish',
        ),
    ]
