# Generated by Django 3.2.9 on 2022-04-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20220403_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daydish',
            name='is_additional',
        ),
        migrations.AddField(
            model_name='daydish',
            name='additional_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.daydish'),
        ),
    ]
