# Generated by Django 3.2.9 on 2022-05-21 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_daydish_additional_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
