# Generated by Django 3.2.9 on 2022-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20220521_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
