# Generated by Django 3.2.9 on 2022-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
